title: "The Blue Goose"
subtitle: "U.S.S. Honolulu (CL-48)"
description: "A memorial to James Ervin ‘Snowie’ Zittel, the U.S.S. Honolulu, and the sailors who served aboard her."
url: ""
baseurl: ""
permalink: pretty
markdown: kramdown
collections:
  crew:
    output: true
    permalink: /crew/:name/
  accounts:
    output: true
    permalink: /accounts/:name/
defaults:
  - scope: {path: "", type: crew}
    values: {layout: crew-profile}
  - scope: {path: "", type: accounts}
    values: {layout: account}
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
